### ISSUE TITLE
Allow usage of arrows in CLI 

### ISSUE THREAD

**Issue by Ocaenyth** [containous/yaegi#286] opened 2019-07-26 07:58 UTC
Currently the interpreter does not support moving around what you have written with the arrow keys.
Say you noticed you made a typo at the start of your command like `ft.Println("hey")`, you'd have to erase everything just to add the missing "m" in `fmt`, instead of going to the desired location using the arrow keys

I guess it could deserve its own issue, but adding command historic could be nice by using `up` and `down` arrows ?

Current behavior: Using the arrow keys writes their "code" in the interpreter
```
$ yaegi
> ^[[D
```
Expected behavior: move the cursor in the interpreter

**Comment by bogen85** [comment] 2019-07-26 11:59
I think the goal is not to use outside libraries.
"Written in pure Go, using only the standard library"

I wrote my own REP loop (copied and modified the existing REP loop) and am using "github.com/peterh/liner" for input.

**Comment by Ocaenyth** [comment] 2019-07-26 14:11
Yeah I see, I guess I skipped that part in the README.
I've been looking around, and while there are better solutions that exist as external libraries, you can also achieve this with only the standard library, as seen in this snippet of code (from [this SO answer](https://stackoverflow.com/questions/15159118/read-a-character-from-standard-input-in-go-without-pressing-enter/17278776#17278776)):
```golang
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	// disable input buffering
	exec.Command("stty", "-F", "/dev/tty", "cbreak", "min", "1").Run()
	// do not display entered characters on the screen
	exec.Command("stty", "-F", "/dev/tty", "-echo").Run()

	size := 5
	var b []byte = make([]byte, size)
	for {
		os.Stdin.Read(b)
		fmt.Println("I got the byte", b, "("+string(b)+")")

                // This is only used to refresh the buffer's memory,
                // I know it's not the best option but I just wanted something
                // that worked for this example.
		b = make([]byte, size)
	}
}
```

Now I know it's more of a workaround for UNIX environments, but this allows to get every input, and you should be able to differentiate the arrow keys. There is still the question of how to manage the cursor but I believe it's doable.

All in all, I don't know if there are reasons, besides the challenge probably, to not use any external libraries, but I think there should be ways to implement it regardless. If not then we could still close this issue

**Comment by bogen85** [comment] 2019-07-27 13:57
@Ocaenyth  Agreed. Windows gives you line editing by default. In Linux other line editing is needed.  [Rlwrap](https://linux.die.net/man/1/rlwrap) works on Linux but it would be better for it to be native.  I prefer not to use Rlwrap. I have my own project where I'll be using Yaegi, so for my immediate needs it is not an issue. But to encourage wide spread use of Yaegi it would be nice if it was on par with, say, Python, in regard to it's REPL feel.

**Comment by bogen85** [comment] 2019-07-29 10:46
@Ocaenyth using external libraries makes a project like Yaegi (when they become stable) hard to get approval for use in some large compaines. Getting approval for Yaegi would be difficult any enough, but for each external library it depends on, it makes it much harder. All that needs to be done (in my opinion) to better support Linux line editing is to include an example for doing your own REP by including the needed Yaegi components.

See https://github.com/bogen85/yaelgat for such an example.

As a companion project to yaegi something that has better line editor support is fine. But that is not really needed. As the readme for yaegi says:

Command-line executable
```
go get -u github.com/containous/yaegi/cmd/yaegi

Note that you can use rlwrap (install with your favorite package manager), and alias the yaegi command in alias yaegi='rlwrap yaegi' in your ~/.bashrc, to have history and command line edition.
```

**Comment by mpl** [comment] 2020-08-26 15:11
Duplicate of #315

**Closed by mpl** 2020-08-26 15:11 UTC
Labels: area/repl, enhancement
