### ISSUE TITLE
Unable to build Yaegi using Go 1.14 (rc1)

### ISSUE THREAD

**Issue by mewmew** [containous/yaegi#511] opened 2020-02-11 19:10 UTC
Thanks for your continued work on Yaegi. It's still such an impressive feat to have an interpreter for the entire Go spec!

I tried to `go get` Yaegi today using Go 1.14 (rc1). However, it seems that the `stdlib` failed to build due to `+build tags`? E.g.

```
$ cat stdlib/go1_13_archive_tar.go 
// Code generated by 'goexports archive/tar'. DO NOT EDIT.

// +build go1.13,!go1.14
```

Error from `go get`:

```
$ go get -v github.com/containous/yaegi/cmd/yaegi
github.com/containous/yaegi (download)
goget/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:44:2: build constraints exclude all Go files in /home/u/goget/src/github.com/containous/yaegi/stdlib
```

Go version:

```
$ go version
go version devel +88ae4ccefb Wed Feb 5 20:54:27 2020 +0000 linux/amd64
```

Cheers,
Robin

**Comment by mewmew** [comment] 2020-02-11 19:20
I tried to re-generate the `stdlib` package using `make gen_all_syscall`, but then ran into the following errors:

```
$ make gen_all_syscall
go generate cmd/goexports/goexports.go
syscall_aix_ppc64.go
can't load package: package .: build constraints exclude all Go files in /home/u/goget/src/github.com/containous/yaegi/stdlib/syscall
syscall_android_386.go
can't load package: package .: build constraints exclude all Go files in /home/u/goget/src/github.com/containous/yaegi/stdlib/syscall
syscall_android_amd64.go
```

**Comment by ldez** [comment] 2020-02-11 19:54
Hello,

Hello,

For now, Yaegi works only with go1.12 and go1.13 due to [stdlib mapping](https://github.com/containous/yaegi/tree/master/stdlib).

But as soon as the first stable 1.14 will be available we will add the support.

https://github.com/containous/yaegi#features

Duplicate of #304, #285

**Closed** 2020-02-26 14:06 UTC
Labels: duplicate
