### ISSUE TITLE
opcode 'not' not work

### ISSUE THREAD

**Issue by kesonIT** [containous/yaegi#475] opened 2019-12-20 08:53 UTC
The following program print wrong result

```go
c := false
println("c || !c = ", c || !c)
println("!c || c = ", !c || c)
```

Expected result:
```
c || !c =  true
!c || c =  true
```

Got:
```
c || !c =  false
!c || c =  false
```

**Comment by ldez** [comment] 2019-12-20 08:56
duplicate of #471

**Comment by ldez** [comment] 2019-12-20 08:57
Take a look to https://github.com/containous/yaegi/issues/474#issuecomment-567845942

**Closed by ldez** 2019-12-20 08:56 UTC
Labels: duplicate
