### ISSUE TITLE
support gopls for auto completion

### ISSUE THREAD

**Issue by laoshaw** [containous/yaegi#801] opened 2020-08-04 18:18 UTC
godoc is out of date and gopls is in use these days, can yaegi support gopls for auto completion?

**Comment by mpl** [comment] 2020-08-05 15:13
Duplicate of #315 
Closing because I believe using gopls to achieve completion is an implementation detail. We can mention gopls on #315 for we if we ever come back on the subject.

**Closed by mpl** 2020-08-05 15:13 UTC
