### ISSUE TITLE
crash regardless of arguments

### ISSUE THREAD

**Issue by robpike** [containous/yaegi#304] opened 2019-07-29 22:53 UTC
I'm very excited about this project but all I can get is a panic immediately on startup. I installed with `go get -u github.com/containous/yaegi/cmd/yaegi`.

```
% ls p.go
p.go
% yaegi p.go
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/containous/yaegi/interp.goNumVersion(0x2)
	/Users/r/src/github.com/containous/yaegi/interp/build.go:91 +0xa5
github.com/containous/yaegi/interp.init()
	/Users/r/src/github.com/containous/yaegi/interp/build.go:60 +0x26
% yaegi
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/containous/yaegi/interp.goNumVersion(0xc00009a1c0)
	/Users/r/src/github.com/containous/yaegi/interp/build.go:91 +0xa5
github.com/containous/yaegi/interp.init()
	/Users/r/src/github.com/containous/yaegi/interp/build.go:60 +0x26
% yaegi -help
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/containous/yaegi/interp.goNumVersion(0xc0000a61b0)
	/Users/r/src/github.com/containous/yaegi/interp/build.go:91 +0xa5
github.com/containous/yaegi/interp.init()
	/Users/r/src/github.com/containous/yaegi/interp/build.go:60 +0x26
% go version
go version devel +54c6b814ac Tue Jul 2 20:07:52 2019 +0000 darwin/amd64
% uname -a
Darwin bismarck.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
% 
```

**Comment by ldez** [comment] 2019-07-29 23:01
Hello,

Yaegi only works with go1.11 and go1.12

Duplicate of #285

**Comment by robpike** [comment] 2019-07-29 23:03
Well, that's easy. Thanks for the quick reply.

**Closed** 2019-07-29 23:04 UTC
Labels: duplicate

**Comment by ldez** [comment] 2019-07-29 23:10
We can allow the use of any version of Go, if we change the way of handling the build tags and if you provide manually the stdlib mapping (by using our `goexports` tool)

**Comment by robpike** [comment] 2019-07-29 23:26
I am happy to wait for 1.13 support. I got it running with 1.12 but the first program I wanted to use it with has some 1.13 features, so it's clear I should just wait.
